server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /chart-query/ {
        proxy_pass https://dash.astronauts.id/;
        proxy_http_version 1.1;
        proxy_set_header Host dash.astronauts.id;
        proxy_set_header Origin https://dash.astronauts.id;
        proxy_set_header Referer https://dash.astronauts.id;
        
        # Rewrite X-Superset-Cookie header to Cookie header
        proxy_set_header Cookie $http_x_superset_cookie;
        
        proxy_ssl_server_name on;
        proxy_ssl_name dash.astronauts.id;
        proxy_ssl_protocols TLSv1.2 TLSv1.3;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
